### ISSUE TITLE
Spargel extensions

### ISSUE THREAD

**Issue by vasia** [project-flink/flink-graph#34]
Currently, Spargel models a vertex as Tuple2 and an edge as Tuple3. We should extend it to operate on the vertex and edge objects.
Then, we can also extend it so that vertices can access their in/out degrees and the total number of vertices of the graph, inside a Spargel iteration. Since we don't allow structural changes within an iteration, we can precompute these values and store them at the vertex object.

**Comment by vasia** [comment]
I guess there's no need copying the spargel record classes, right?

**Comment by StephanEwen** [comment]
You are right, please drop those. The Record API is deprecated anyways.
