### ISSUE TITLE
Join edges with some input data set

### ISSUE THREAD

**Issue by ktzoumas** [project-flink/flink-graph#45]
Similar to Graph.joinWithVertices it would be useful to have a Graph.joinWithEdges method.

I would suggest to have three methods

joinWithEdges -- expects a DataSet of Tuple3 and joins on the composite key of both source and target

joinWithEdgesOnSource -- expects a DataSet of Tuple2 and joins on the source key of the edges and the first attribute of the input data set

joinWithEdgesOnTarget -- expects a DataSet of Tuple2 and joins on the target key of the edges and the first attribute of the input data set

All of these would take as parameter a MapFunction with the edge value and the input data set value

**Comment by andralungu** [comment]
I will work on this one. Just a quick question: since we're performing a join, what happens when some ids from the initial set of edges cannot be found in the DataSet given as a parameter? Do we keep the edge value(like in joinWithVertices) or do we remove it from the result?

**Comment by vasia** [comment]
Hi Andra!

I think it's better to be consistent with the joinWithVertices and keep the
edge value.

-V.

**Comment by andralungu** [comment]
Hello,

For joinWithEdgesOnSource, what happens if the inputDataSet contains the same key twice? Which value do you take? Do you do something like a cross between them?

Thanks!

**Comment by vasia** [comment]
Hi @andralungu! 
This is a great question relevant to all "joinWith" methods.
We could either (a) just consider the first value (like joinWithVertices does now) and document the behavior or (b) provide all values of the key to the user function.
Personally, I like (a) because it keeps the user code simple. The multiple-value case can always be realized using a group before the" joinWith" method.
What do you think?

**Comment by andralungu** [comment]
Hi @vasia !

I will go with (a) because it resembles joinWIthVertices and due to its simplicity :). If someone has another opinion later on, I could change the implementation.

**Comment by vasia** [comment]
Implemented in #49.
