### ISSUE TITLE
TestReduceOnNeighborMethods is failing

### ISSUE THREAD

**Issue by vasia** [project-flink/flink-graph#50]
The 3 last cases in TestReduceOnNeighborMethods fail on`testJobWithObjectReuse`.
Was there any recent change that might have triggered this? The test was passing until yesterday.

**Comment by StephanEwen** [comment]
I assume you are using the latest master.
Can you post the type of the failure?

There were a few commits today that may have effects:

[FLINK-1245] introduced the type hints (I will send a separate mail about those, they will make you life much easier) and it could be that we introduced a bug.

Possible is also  [FLINK-1285] (from yesterday), where now objects are not reused any more. I you had that assumption in the code, it may cause your code to behave differently.

**Comment by vasia** [comment]
Latest master, yes.
The failure is the following:
```
Failed tests:   testJobWithObjectReuse[3](flink.graphs.TestReduceOnNeighborMethods): arrays first differed at element [2]; expected:<[3,9]> but was:<[4,5]>
  testJobWithObjectReuse[4](flink.graphs.TestReduceOnNeighborMethods): arrays first differed at element [2]; expected:<[3,59]> but was:<[4,102]>
  testJobWithObjectReuse[5](flink.graphs.TestReduceOnNeighborMethods): arrays first differed at element [2]; expected:<[3,12]> but was:<[4,8]>
```
It seems that it has to do with FLINK-1285 indeed. When/how is object reuse enabled and how can I make the code aware of this?
Thanks :)

**Comment by aljoscha** [comment]
Hi,
object reuse is enabled/disabled using ExecutionEnvironment.getConfig().enableObjectReuse()/disableObjectReuse().

I can look into the error in a bit. (When I get to the office.)

**Comment by vasia** [comment]
Thanks a lot guys ^^ 
I guess reuse is disabled by default?

**Comment by StephanEwen** [comment]
Yes it is deactivated by default. It is actually the simpler and safer way will fewer implicit assumptions.
