### ISSUE TITLE
Add tests for the library methods and the examples

### ISSUE THREAD

**Issue by vasia** [project-flink/flink-graph#59]
All the tests we have now test one method at a time. We should have some tests for complete applications. As a start, we could add one test case per example and this way also make sure that our graph library methods actually give correct results :)

**Comment by andralungu** [comment]
I will write the test for SSSP.

**Comment by vasia** [comment]
Moved to [FLINK-1522](https://issues.apache.org/jira/browse/FLINK-1522).
