### ISSUE TITLE
description or behavior of Graph.reverse() not correct

### ISSUE THREAD

**Issue by cebe** [project-flink/flink-graph#60]
https://github.com/project-flink/flink-graph/blob/23310d928e2eaf09a8233503bec539deca41273f/src/main/java/flink/graphs/Graph.java#L671

The exception message complains about undirected and also the newly created graph is undirected. This does not look right to me.

**Comment by vasia** [comment]
Yes, you're right. The exception message should be changed to something like "not possible to reverse an undirected graph" and the `undirectedEdges` variable name is misleading and should be changed to something like `reversedEdges`.
