### ISSUE TITLE
Concept of undirected graph is not clear

### ISSUE THREAD

**Issue by cebe** [project-flink/flink-graph#61]
most methods return a directed graph after doing their job even if they are working on an undirected graph because they forget to pass the boolean value to the new Graph object.

In general I do not think it is a good idea to pass a boolean around to track whether a graph is directed or not. It may be better to have the difference between directed and undirected using subclasses.

Ideas, opinions?

**Comment by vasia** [comment]
We've had this discussion some time ago and decided to always treat a graph as directed for moment, for simplicity. I'm copying from our meeting minutes:

_We assume that a graph is by default directed and model the undirected graph by generating the opposite direction edges. Vasia doesn't like this of (a) data duplication, (b) inconsistencies (always needing to keep the two edges consistent, e.g. when the value one edge changes, make sure that this is also reflected on the opposite edge or mitigate this to the programmer). We will consider another solution in the future._

I think that with this assumption, there is no need for the boolean and we can delete it. The api methods will always consider the graph as directed and an undirected graph is simply a graph with the opposite direction edges added.
